### ISSUE TITLE
TS Support

### ISSUE THREAD

**Issue by andrieshiemstra** [HiRoFa/starlight_runtime#1]
see if we can get that native in SL

for qjs it should be an optional feature in utils (generic TS transpiler)

**Comment by playXE** [comment]
Starlight uses SWC to parse JS and SWC can convert TS to JS but it lacks type checking and because of this I didn't yet have TS support.

**Comment by andrieshiemstra** [comment]
Yeah i figured the SWC options could be altered so it can read TS, instead of doing type checking in starlight it might be simpler to transpile to JS (with typechecking) in debug mode and just read TS (without typechecking) in release mode (TS without typechecking is faster, allthough some people might disagree with this way of working, we could allways make it optional).

i'm playing around with TS [here](https://github.com/HiRoFa/typescript_utils)
